development:
  adapter: mysql2
  encoding: utf8
  database: authentication_development
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: authentication_test
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: authentication_production
  username: root
  password:
